name: Test & Deploy
on:
  push:
    branches:
      - master
jobs:
  test_deploy:
    name: Test & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Python 3.8.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.6'
      - name: Setup pipenv
        run: |
          sudo pip install pipenv --upgrade
          pipenv --python 3.8.6
          pipenv install -d
      - name: Test
        run: make test
      - name: Setup AWS CDK
        run: |
          curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
          sudo apt-get -y -qq install nodejs
          sudo npm i -g aws-cdk
      - name: Deploy
        run: |
          AWS_DEFAULT_REGION="us-east-1" \
          AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
          AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          AGGRESSIVE_PORTFOLIO_KEY="${{ secrets.AGGRESSIVE_PORTFOLIO_KEY }}" \
          AGGRESSIVE_PORTFOLIO_SECRET="${{ secrets.AGGRESSIVE_PORTFOLIO_SECRET }}" \
          AGGRESSIVE_PORTFOLIO_PASSPHRASE="${{ secrets.AGGRESSIVE_PORTFOLIO_PASSPHRASE }}" \
          MARKET_CAP_PORTFOLIO_KEY="${{ secrets.MARKET_CAP_PORTFOLIO_KEY }}" \
          MARKET_CAP_PORTFOLIO_SECRET="${{ secrets.MARKET_CAP_PORTFOLIO_SECRET }}" \
          MARKET_CAP_PORTFOLIO_PASSPHRASE="${{ secrets.MARKET_CAP_PORTFOLIO_PASSPHRASE }}" \
          cdk deploy --require-approval never --verbose
